import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — LiveLink',
}

const EFFECTIVE_DATE = 'June 1, 2025'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: '#111827', marginBottom: 12 }}>{title}</h2>
      <div style={{ fontSize: 15, color: '#4B5563', lineHeight: 1.75 }}>{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <>
      <div style={{ marginBottom: 48 }}>
        <p style={{ fontSize: 12, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#16C064', marginBottom: 10 }}>Legal</p>
        <h1 className="syne" style={{ fontSize: 36, fontWeight: 800, color: '#0A0A0A', lineHeight: 1.15, marginBottom: 10 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: '#9CA3AF' }}>Effective date: {EFFECTIVE_DATE}</p>
      </div>

      <p style={{ fontSize: 15, color: '#4B5563', lineHeight: 1.75, marginBottom: 40 }}>
        These Terms of Service govern your use of LiveLink, operated by <strong style={{ color: '#111827' }}>Trackwise Nigeria Limited</strong> (RC: 9593605). By creating an account or using LiveLink, you agree to these terms. If you do not agree, do not use the service.
      </p>

      <Section title="1. The service">
        <p>
          LiveLink is a pay-as-you-go delivery tracking platform that enables vendors to generate real-time GPS tracking links for their riders and customers. The service is provided on an &ldquo;as is&rdquo; basis. We do not employ or manage riders — we provide tools for vendors who use their own delivery personnel.
        </p>
      </Section>

      <Section title="2. Account registration">
        <p style={{ marginBottom: 12 }}>To use LiveLink as a vendor, you must:</p>
        <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <li>Provide accurate information during registration.</li>
          <li>Be at least 18 years of age.</li>
          <li>Keep your account credentials confidential.</li>
          <li>Be responsible for all activity that occurs under your account.</li>
        </ul>
        <p style={{ marginTop: 12 }}>We reserve the right to suspend or terminate accounts that violate these terms or are used for fraudulent purposes.</p>
      </Section>

      <Section title="3. Credit system and payments">
        <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <li>LiveLink uses a prepaid credit system. Each tracking delivery costs one credit.</li>
          <li>Credits are purchased in advance via Paystack. All purchases are in Nigerian Naira (₦).</li>
          <li>Credits do not expire and are non-transferable between accounts.</li>
          <li>Credits are deducted at the point of creating a delivery, not at completion.</li>
          <li><strong style={{ color: '#111827' }}>Credits are non-refundable</strong> once deducted, except where a technical error on our part prevented the delivery from being created. Contact us within 48 hours of such an incident.</li>
          <li>New accounts receive 5 complimentary credits upon registration. These are also non-refundable and non-transferable.</li>
        </ul>
      </Section>

      <Section title="4. Acceptable use">
        <p style={{ marginBottom: 12 }}>You agree not to use LiveLink to:</p>
        <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 8 }}>
          <li>Track any person without their knowledge or consent.</li>
          <li>Facilitate illegal deliveries, including controlled substances or prohibited goods.</li>
          <li>Abuse, harass, or defraud customers or riders.</li>
          <li>Attempt to reverse-engineer, scrape, or overload the platform.</li>
          <li>Share your account access or resell the service without written permission.</li>
        </ul>
        <p style={{ marginTop: 12 }}>We may suspend access immediately and without notice for serious violations of this section.</p>
      </Section>

      <Section title="5. GPS tracking and rider consent">
        <p>
          By sending a rider link generated by LiveLink, you confirm that the rider is aware their location will be tracked during the delivery and has consented to this. Trackwise Nigeria Limited is not responsible for any dispute arising from tracking performed without proper consent.
        </p>
      </Section>

      <Section title="6. Service availability">
        <p>
          We aim for high availability but do not guarantee uninterrupted service. Scheduled maintenance, third-party outages (Supabase, Vercel), and events beyond our control may cause downtime. We will not be liable for losses resulting from service unavailability.
        </p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>
          To the maximum extent permitted by Nigerian law, Trackwise Nigeria Limited shall not be liable for any indirect, incidental, or consequential damages arising from your use of LiveLink — including but not limited to lost sales, delivery disputes, customer complaints, or data loss. Our total liability to you in any month shall not exceed the value of credits purchased in that month.
        </p>
      </Section>

      <Section title="8. Intellectual property">
        <p>
          All software, design, and content of LiveLink is owned by Trackwise Nigeria Limited. You may not copy, reproduce, or create derivative works without written permission. Your delivery data (customer names, notes, location history) belongs to you and we will not use it for any purpose other than providing the service.
        </p>
      </Section>

      <Section title="9. Governing law">
        <p>
          These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved in the courts of the Federal Capital Territory, Abuja.
        </p>
      </Section>

      <Section title="10. Changes to these terms">
        <p>
          We may update these terms at any time. Registered vendors will be notified by email at least 14 days before material changes take effect. Continued use of the service after the effective date constitutes acceptance of the updated terms.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these terms? Reach us at:<br />
          Trackwise Nigeria Limited · RC 9593605<br />
          Email: <a href="mailto:info@livelink.ng" style={{ color: '#16C064' }}>info@livelink.ng</a>
        </p>
      </Section>
    </>
  )
}
